Update tutorial screenshots
FlexMeasures/screenshots pull request #1
Opened 2023-05-18 13:43 UTC by Ahmad-Wahid

- Added new asset view with and without data .
- New screenshot of battery discharge.
-  Updated day-ahead-prices screenshot.

2023-05-18 14:09 UTC, nhoening commented
Quick comment: If we rename screenshots, older versions of the documentation will not show properly anymore.

In a perfect world, we'd find a way to manage the screenshots in a different way, but there is no perfect design we can think of. 

Why do we need screenshots without data anyway?

2023-05-18 14:39 UTC, Ahmad-Wahid commented
I added it because, if you look at the first asset screenshot in the tutorial, it just shows the battery sensor, location, and editing options of the asset.

2023-05-18 20:00 UTC, nhoening requested changes
Following up on my previous comment (which you did not reply to), I'm making some suggestions myself on how to keep older docs version working,

2023-05-18 20:00 UTC, nhoening commented on tut/toy-schedule/sensor-data-discharging-solar.png
I know you chose the name as it fits the title, but I'd keep the title as it otherwise breaks previous docs versions (and both charging and discharging actually happens).

2023-05-18 20:00 UTC, nhoening commented on tut/toy-schedule/asset-view-with-data.png
Let's keep the name here as `asset-view.png`, to keep older docs versions working.

2023-05-18 20:33 UTC, nhoening commented on tut/toy-schedule/sensor-data-discharging-solar.png
Sorry, that was a wrong assumption - this one is new. I'd rename it with "charging" as well, for consistency.

I would use "charging" in `sensor-data-discharging.png`, as per my comment above.

2023-05-19 05:08 UTC, Ahmad-Wahid commented on tut/toy-schedule/sensor-data-discharging-solar.png
okay understood.

2023-05-19 05:08 UTC, Ahmad-Wahid commented on tut/toy-schedule/sensor-data-discharging-solar.png
okay understood.

2023-05-19 15:42 UTC, Flix6x reviewed
Looks good.

Note that in https://github.com/FlexMeasures/flexmeasures/pull/687 I request one extra screenshot, so you might as well include it in this PR.

2023-05-22 07:31 UTC, Flix6x approved these changes

2023-05-23 07:42 UTC, nhoening approved these changes

2023-05-23 08:41 UTC, merged